services:
  # Backend service
  - type: web
    name: superadmin-backend
    env: node
    rootDir: Backend          # 👈 this tells Render to use Backend/package.json
    buildCommand: "npm install && npx prisma generate && npx prisma migrate deploy"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  # Frontend service
  - type: static_site
    name: superadmin-frontend
    rootDir: frontend         # 👈 this tells Render to use frontend/package.json
    buildCommand: "npm install && npm run build"
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://superadmin-backend.onrender.com/api/v1
